services:
  frontend:
    build:
      context: .
      args:
        - SERVER_URL=${SERVER_URL}
        - WEATHER_SERVER_URL=${WEATHER_SERVER_URL}
        - WEATHER_API_KEY=${WEATHER_API_KEY}
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      - SERVER_URL=${SERVER_URL}
      - WEATHER_SERVER_URL=${WEATHER_SERVER_URL}
      - WEATHER_API_KEY=${WEATHER_API_KEY}