FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
ARG NEXT_PUBLIC_SERVER_URL
ARG NEXT_PUBLIC_WEATHER_SERVER_URL
ARG NEXT_PUBLIC_WEATHER_API_KEY
ENV NEXT_PUBLIC_SERVER_URL=$NEXT_PUBLIC_SERVER_URL
ENV NEXT_PUBLIC_WEATHER_SERVER_URL=$NEXT_PUBLIC_WEATHER_SERVER_URL
ENV NEXT_PUBLIC_WEATHER_API_KEY=$NEXT_PUBLIC_WEATHER_API_KEY
RUN npm run build
EXPOSE 3000
CMD ["npm", "start"]