server {
    listen 0.0.0.0:3000;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # location /api/ {
    #     set $backend_host "http://127.255.0.1:8080"; 
        
    #     rewrite ^/api/(.*)$ /$1 break;
        
    #     proxy_pass $backend_host;
        
    #     # ZMIANA: Zamiast $host, podaj nazwę usługi, którą odpytujesz
    #     proxy_set_header Host taskhelldb;
        
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header X-Forwarded-Proto $scheme;
    # }

    location /api/ {
        # Używamy uniwersalnego adresu DNS dla sieci AWS VPC (pula 169.254.X.X).
        # Ten resolver potrafi rozkodować pełne nazwy wraz z namespace (np. .taskhell-namespace).
        resolver 172.168.0.2 169.254.169.253 valid=5s;
        proxy_set_header Host $host;
        
        # Definiujemy backend za pomocą pełnej nazwy domeny Service Connect i portu
        set $backend_host "http://taskhelldb.taskhell-namespace:8080"; 
        
        # Wycinamy przedrostek /api/ przed przekazaniem żądania dalej
        rewrite ^/api/(.*)$ /$1 break;
        
        proxy_pass $backend_host;

        # --- DODAJ TE LINIE, ABY PRZEPUSZCZAĆ TOKEN JWT ---
        proxy_pass_header Authorization;
        proxy_pass_header Bearer;
        
        # Jeśli token jest zwracany w nagłówkach, CORS musi pozwolić skryptom na jego odczyt
        add_header 'Access-Control-Expose-Headers' 'Authorization' always;
        
        # # Nagłówki przekazujące oryginalne dane klienta
        # proxy_set_header Host taskhelldb;
        # proxy_set_header X-Real-IP $remote_addr;
        # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # proxy_set_header X-Forwarded-Proto $scheme;
    }
}
