export const metadata = {
  title: "TaskHell",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body data-theme="light">
        {children}
      </body>
    </html>
  );
}
