export const metadata = {
  title: "TaskHell",
  description: "Generated by create next app",
  icons: {
    icon: "/logo/taskhell_concept.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body data-theme="light">
        {children}
      </body>
    </html>
  );
}
