const procrastinationTasks = [
    "Learn the basics of Morse code.",
    "Research how CRT displays work.",
    "Try to learn the alphabet in sign language.",
    "Watch a tutorial on how to juggle 3 balls.",
    "Read the Wikipedia page for a randomly selected historical event.",
    "Figure out how your microwave actually heats food.",
    "Draw a map of a fictional place.",
    "Try to fold a piece of paper more than 7 times (and research why it's hard).",
    "Learn to tie 5 different types of knots.",
    "Find out the history of your favorite snack food.",
    "Explore a random location on Google Street View for 15 minutes.",
    "Listen to a genre of music you've never heard before.",
    "Attempt to write a haiku about procrastination.",
    "Learn the NATO phonetic alphabet (Alpha, Bravo, Charlie...).",
    "Research the basics of how cryptocurrency blockchain works.",
    "Find and watch a live nature cam online (e.g., birds, bears, ocean).",
    "Try to solve a Rubik's Cube (even just one side).",
    "Plan a hypothetical trip to Mars.",
    "Learn a simple magic trick involving cards or coins.",
    "Read about a conspiracy theory you find interesting (for entertainment only!).",
    "Try basic origami: fold a crane or a boat.",
    "Design your dream treehouse layout.",
    "Look up the etymology (origin) of 5 common words.",
    "Try identifying 3 constellations visible tonight (use an app/website).",
    "Write a short story where the main character is an inanimate object.",
    "Learn how to whistle loudly using your fingers.",
    "Research the different types of clouds and try to identify some outside.",
    "Create a playlist for a very specific, unusual mood (e.g., 'Cyberpunk rainy Tuesday').",
    "Try drawing something using only ASCII characters.",
    "Learn the rules of a board game or card game you've never played.",
    "Watch a documentary on a topic you know nothing about.",
    "Try to write your name legibly with your non-dominant hand.",
    "Explore the 'random article' feature on Wikipedia for 20 minutes.",
    "Learn about the history of video games.",
    "Try pixel art: create a small sprite.",
    "Research how bioluminescence works in deep-sea creatures.",
    "Invent a secret handshake.",
    "Find the weirdest product currently for sale on eBay or Etsy.",
    "Translate the lyrics of your favorite song into emojis.",
    "Learn how to beatbox a basic rhythm.",
    "Read about the Dunning-Kruger effect.",
    "Try to identify 5 different bird calls (use online resources).",
    "Design a flag for your bedroom or workspace.",
    "Learn the basic principles of lock picking (understanding tumbler locks).",
    "Research unusual or extinct animals.",
    "Try 'blackout poetry' with a newspaper page or old book page.",
    "Figure out your 'astronaut name' (using a silly online generator or formula).",
    "Watch a time-lapse video of something interesting (e.g., plant growth, city traffic).",
    "Learn about different logical fallacies.",
    "Try finger knitting or making a friendship bracelet.",
    "Research how touch screens actually work.",
    "Learn 5 basic calligraphy strokes.",
    "Watch a video explaining the history of animation.",
    "Try to understand the basic difference between nuclear fission and fusion.",
    "Learn how vinyl records store and reproduce sound.",
    "Research deepfake technology: how it's made and detected.",
    "Read about 3 different logical paradoxes (like the Ship of Theseus).",
    "Study the history and design choices of a specific font (e.g., Helvetica).",
    "Learn the basic principles of how GPS satellites navigate.",
    "Research optical illusions and find explanations for why 2-3 examples work.",
    "Understand the meaning of the word 'sonder'.",
    "Read about techniques for lucid dreaming.",
    "Explore the mystery of the Voynich Manuscript online.",
    "Learn the flags of 10 countries you know little about.",
    "Understand the basics of color theory (primary, secondary, complementary).",
    "Find 3 examples of biomimicry in design or technology.",
    "Try making a short stop-motion animation (5-10 seconds) using phone/webcam and objects.",
    "Write a poem or short paragraph from the perspective of a common household object.",
    "Create a character profile (name, abilities, backstory) based on the nearest lamp.",
    "Experiment with a free online generative art tool.",
    "Try to make a simple musical instrument from household items (e.g., tissue box guitar).",
    "Design a fictional currency, including symbols and denominations.",
    "Write a fake 'breaking news' report about something completely mundane happening outside.",
    "Try blind contour drawing: draw your own hand without looking at the paper.",
    "Create a digital or physical 'mood board' for an imaginary project.",
    "Write overly complex, step-by-step instructions for making toast.",
    "Explore the Internet Archive's Wayback Machine: look up an old version of a favorite website.",
    "Find and listen to a podcast episode about a historical mystery or unsolved crime.",
    "Browse the online collection of a famous museum you've never visited.",
    "Listen to 15 minutes of traditional folk music from a random country.",
    "Explore open-source software alternatives for a program you regularly use.",
    "Use online satellite maps to find interesting geographical formations.",
    "Read funny one-star reviews of classic books or movies.",
    "Discover and read a new webcomic for 20 minutes.",
    "Use a 'radio garden' website to listen to random radio stations from around the world.",
    "Try an online KenKen or Nonogram puzzle.",
    "Learn the optimal strategy for playing 'Dots and Boxes'.",
    "Play an online typing game to test and improve your speed.",
    "Attempt a challenging logic grid puzzle.",
    "Learn the basic rules and opening moves of the board game Go.",
    "Try to learn a simple coin roll or vanishing trick.",
    "Practice shuffling a deck of cards using different techniques (overhand, riffle, bridge).",
    "Try to balance a broom vertically on your hand.",
    "Attempt to learn a basic pen spinning trick (like the ThumbAround).",
    "Mimic the walk or sound of 3 different animals.",
    "Create a ridiculously specific Pinterest board (e.g., 'Pictures of Squirrels Wearing Hats').",
    "Try to find the oldest comment still visible on a popular YouTube video.",
    "Take an online personality quiz (like a 'Which type of bread are you?' one).",
    "Design a simple one-page website using a free platform like Carrd or Notion.",
    "Read about a famous historical hoax or prank.",
    "Research how touch screens actually work.",
    "Learn 5 basic calligraphy strokes.",
    "Watch a video explaining the history of animation.",
    "Try to understand the basic difference between nuclear fission and fusion.",
    "Learn how vinyl records store and reproduce sound.",
    "Research deepfake technology: how it's made and detected.",
    "Read about 3 different logical paradoxes (like the Ship of Theseus).",
    "Study the history and design choices of a specific font (e.g., Helvetica).",
    "Learn the basic principles of how GPS satellites navigate.",
    "Research optical illusions and find explanations for why 2-3 examples work.",
    "Understand the meaning of the word 'sonder'.",
    "Read about techniques for lucid dreaming.",
    "Explore the mystery of the Voynich Manuscript online.",
    "Learn the flags of 10 countries you know little about.",
    "Understand the basics of color theory (primary, secondary, complementary).",
    "Find 3 examples of biomimicry in design or technology.",
    "Try making a short stop-motion animation (5-10 seconds) using phone/webcam and objects.",
    "Write a poem or short paragraph from the perspective of a common household object.",
    "Create a character profile (name, abilities, backstory) based on the nearest lamp.",
    "Experiment with a free online generative art tool.",
    "Try to make a simple musical instrument from household items (e.g., tissue box guitar).",
    "Design a fictional currency, including symbols and denominations.",
    "Write a fake 'breaking news' report about something completely mundane happening outside.",
    "Try blind contour drawing: draw your own hand without looking at the paper.",
    "Create a digital or physical 'mood board' for an imaginary project.",
    "Write overly complex, step-by-step instructions for making toast.",
    "Explore the Internet Archive's Wayback Machine: look up an old version of a favorite website.",
    "Find and listen to a podcast episode about a historical mystery or unsolved crime.",
    "Browse the online collection of a famous museum you've never visited.",
    "Listen to 15 minutes of traditional folk music from a random country.",
    "Explore open-source software alternatives for a program you regularly use.",
    "Use online satellite maps to find interesting geographical formations.",
    "Read funny one-star reviews of classic books or movies.",
    "Discover and read a new webcomic for 20 minutes.",
    "Use a 'radio garden' website to listen to random radio stations from around the world.",
    "Try an online KenKen or Nonogram puzzle.",
    "Learn the optimal strategy for playing 'Dots and Boxes'.",
    "Play an online typing game to test and improve your speed.",
    "Attempt a challenging logic grid puzzle.",
    "Learn the basic rules and opening moves of the board game Go.",
    "Try to learn a simple coin roll or vanishing trick.",
    "Practice shuffling a deck of cards using different techniques (overhand, riffle, bridge).",
    "Try to balance a broom vertically on your hand.",
    "Attempt to learn a basic pen spinning trick (like the ThumbAround).",
    "Mimic the walk or sound of 3 different animals.",
    "Create a ridiculously specific Pinterest board (e.g., 'Pictures of Squirrels Wearing Hats').",
    "Try to find the oldest comment still visible on a popular YouTube video.",
    "Take an online personality quiz (like a 'Which type of bread are you?' one).",
    "Design a simple one-page website using a free platform like Carrd or Notion.",
    "Read about a famous historical hoax or prank."
  ];

function randomTaskGenerator(){
    const randomIndex = Math.floor(Math.random() * procrastinationTasks.length);
    const randomTask = procrastinationTasks[randomIndex];
    return {
        randomTask
    };
}


export default randomTaskGenerator;